name: Publish
on:
  push:
    tags:
      - 'v*'

permissions:
  # Grant the ability to checkout the repository
  contents: read

jobs:
  publish-docker-images:
    name: Push Docker images
    runs-on: ubuntu-latest
    permissions:
      # Grant the ability to write to GitHub Packages (push Docker images to
      # GitHub Container Registry).
      packages: write
      # Grant the ability to checkout the repository.
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Docker images
        run: make publish-component-containers

      - name: Publish component Helm package
        run: |
          set -e;
          DRACON_VERSION=$(sed 's/v//' <<< ${{ github.ref_name }});
          make cmd/draconctl/bin; \
          bin/cmd/draconctl components package --version ${DRACON_VERSION} --chart-version ${DRACON_VERSION} --name dracon-oss-components ./components; \
          helm push dracon-oss-components-${DRACON_VERSION}.tgz oci://ghcr.io/ocurity/charts
